# Generated by Django 6.1 on 2026-08-28 14:53

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Trip',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(db_index=True, max_length=255)),
                ('description', models.TextField(blank=True, default='')),
                ('start_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('cover_image_url', models.URLField(blank=True, max_length=500, null=True)),
                ('visibility', models.CharField(choices=[('PUBLIC', 'Public'), ('PRIVATE', 'Private'), ('UNLISTED', 'Unlisted')], db_index=True, default='PRIVATE', max_length=20)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='owned_trips', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Trip',
                'verbose_name_plural': 'Trips',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TripCollaborator',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('role', models.CharField(choices=[('ADMIN', 'Admin'), ('EDITOR', 'Editor'), ('VIEWER', 'Viewer')], default='VIEWER', max_length=20)),
                ('joined_at', models.DateTimeField(auto_now_add=True)),
                ('trip', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to='trips.trip')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trip_memberships', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Trip Collaborator',
                'verbose_name_plural': 'Trip Collaborators',
            },
        ),
        migrations.AddField(
            model_name='trip',
            name='collaborators',
            field=models.ManyToManyField(blank=True, related_name='shared_trips', through='trips.TripCollaborator', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='PointOfInterest',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255)),
                ('category', models.CharField(choices=[('ACCOMMODATION', 'Accommodation'), ('FOOD_DRINK', 'Food & Drink'), ('ATTRACTION', 'Attraction / Sightseeing'), ('NATURE', 'Nature & Outdoor'), ('TRANSPORT', 'Transport / Hub'), ('OTHER', 'Other')], db_index=True, default='OTHER', max_length=30)),
                ('notes', models.TextField(blank=True, default='')),
                ('google_place_id', models.CharField(blank=True, db_index=True, help_text='Google Places API unique identifier', max_length=255, null=True)),
                ('source_url', models.URLField(blank=True, help_text='Fallback manual URL (e.g., blog post, Instagram link, direct map pin)', max_length=500, null=True)),
                ('formatted_address', models.CharField(blank=True, default='', max_length=500)),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('sequence_order', models.PositiveIntegerField(default=0, help_text='Order index for manual or AI-generated itineraries')),
                ('is_visited', models.BooleanField(default=False)),
                ('trip', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='points_of_interest', to='trips.trip')),
            ],
            options={
                'verbose_name': 'Point of Interest',
                'verbose_name_plural': 'Points of Interest',
                'ordering': ['sequence_order', 'created_at'],
                'indexes': [models.Index(fields=['trip', 'sequence_order'], name='trips_point_trip_id_74565c_idx')],
            },
        ),
        migrations.AddConstraint(
            model_name='tripcollaborator',
            constraint=models.UniqueConstraint(fields=('trip', 'user'), name='unique_trip_collaborator'),
        ),
    ]
